# Generated by Django 3.2.9 on 2023-04-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image_alt',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travel_extended_description',
            new_name='extended_description',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travel_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travel_image_alt',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travel_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travel_shotr_description',
            new_name='short_description',
        ),
    ]
