# Generated by Django 3.2.9 on 2023-04-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230422_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='main_app/static/img'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(upload_to='main_app/static/img'),
        ),
    ]
