# Generated by Django 3.2.9 on 2023-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230422_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(upload_to='travel'),
        ),
    ]
